config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ships

  resources :customers

   root 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  after_validation :update_fields_complete
  has_many :ships, dependent: :destroy

  def update_fields_complete
    self.fields_complete = check_fields_status
  end

  private
  def check_fields_status
    complete = true
    self.attributes.each do |attr, value|
      complete = false if value.nil? && !id_or_fields_complete(attr)
    end
    complete
  end

  def id_or_fields_complete(attr)
    attr == 'fields_complete' || attr == 'id'
  end


end

app/models/ship.rb
class Ship < ActiveRecord::Base

  belongs_to :customer

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :cellphone, :phone, :address, :rg, :rg_date, :cpf, :mother)
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
    @customer = Customer.find(params[:customer_id])
    @ship = @customer.ships.build
  end

  # GET /ships/1/edit
  def edit
  end

  # POST /ships
  # POST /ships.json
  def create
    @customer = Customer.find(ship_params[:customer_id])
    @ship = @customer.ships.build(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Embarcação criada com sucesso' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :kind, :registration_number, :insurance_due_date, :registration_due_date, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br>
    <%= f.text_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Edição de Cliente</h1>

<%= render 'form' %>
<%= link_to "Criar Embarcação", :controller => "ships", :action => "new", :customer_id => @customer.id %>
<%= link_to 'Ver cliente', @customer %> |
<%= link_to 'Lista de clientes', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>Clientes</h1>
</div>

<div class="col-md-10">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Celular</th>
        <th>Embarcação</th>
        <th>Vencimento do Seguro</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
        <% @ship = customer.ships.last %>
        <tr class='customer-id' id=<%= customer.id %>>
          <td><%= link_to customer.name, customer %></td>
          <td><%= customer.cellphone %></td>
          <% if @ship %>
            <td><%= link_to @ship.name, @ship %></td>
            <td><%= @ship.insurance_due_date %>
          <% else %>
            <td></td><td></td>
          <% end %>
          <% if customer.fields_complete %>
            <td><span class='label label-success'>Dados completos</span></td>
          <% else %>
            <td><span class='label label-danger'>Faltando dados</span></td>
          <% end %>
          <td><%= link_to 'Editar', edit_customer_path(customer) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<p>
  <button type="button" class="btn btn-default">
    <%= link_to 'Criar novo cliente', new_customer_path %>
  </button>
</p>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<div class='page-header'>
  <h1><%= @customer.name %></h1>
</div>

<div class="row">
        <div class="col-md-6">
          <table class="table">
            <tbody>
              <tr>
                <% @customer.attributes.each do |attr| %>
                  <tr>
                    <td><b><%= attr.first %></b><td>
                    <td><%= attr.last %></td>
                  </tr>
                <% end %>
                <% @customer.ships.each do |ship| %>
                  <tr>
                    <td><b>Embarcação</b></td>
                    <td><%= link_to ship.name, ship %><td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>

<p>
  <button type="button" class="btn btn-default">
    <%= link_to 'Editar', edit_customer_path(@customer) %>
  </button>
</p>
<p>
  <button type="button" class="btn btn-default">
    <%= link_to 'Ir para a lista de clientes', customers_path %>
  </button>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="http://ljdespachante.com.br/wp-content/uploads/2014/09/LOGO-arredondado.png">

  <title>L & J Despachante Náutico</title>

  <link href="/bootstrap.min.css" rel="stylesheet">
  <link href="/bootstrap-theme.min.css" rel="stylesheet">
  <link href="/theme.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body role="document">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">L & J Despachante Náutico</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Lista de clientes', customers_path %></li>
                <li><%= link_to 'Criar novo cliente', new_customer_path %></li>
              </ul>
            </li>
            <li><%= link_to 'Embarcações', ships_path %></li>
            <li><%= link_to 'Minha Conta', edit_user_registration_path %></li>
            <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>

  <% unless user_signed_in? %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/ships/_form.html.erb
<%= form_for(@ship) do |f| %>
  <% if @ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
      <% @ship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :registration_number %><br>
    <%= f.text_field :registration_number %>
  </div>
  <div class="field">
    <%= f.label :insurance_due_date %><br>
    <%= f.datetime_select :insurance_due_date %>
  </div>
  <div class="field">
    <%= f.label :registration_due_date %><br>
    <%= f.datetime_select :registration_due_date %>
  </div>
  <div class="field">
    <%= f.label :customer %>
    <%= f.select(:customer_id, Customer.all.collect {|customer| [ customer.name, customer.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing Ship</h1>

<%= render 'form' %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ships</h1>

<div class="col-md-10">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Número de Inscrição</th>
        <th>Vencimento do Seguro</th>
        <th>Vencimento do documento</th>
        <th>Cliente</th>
      </tr>
    </thead>

    <tbody>
      <% @ships.each do |ship| %>
        <tr>
          <td><%= link_to ship.name, ship %></td>
          <td><%= ship.kind %></td>
          <td><%= ship.registration_number %></td>
          <td><%= ship.insurance_due_date %></td>
          <td><%= ship.registration_due_date %></td>
          <td><%= link_to ship.customer.name, ship.customer %>
          <td><%= link_to 'Editar', edit_ship_path(ship) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ships/new.html.erb
<h1>New Ship</h1>

<%= render 'form' %>

<%= link_to 'Back', ships_path %>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ship.name %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @ship.kind %>
</p>

<p>
  <strong>Número de inscrição:</strong>
  <%= @ship.registration_number %>
</p>

<p>
  <strong>Data de vencimento do seguro:</strong>
  <%= @ship.insurance_due_date %>
</p>

<p>
  <strong>Data de vencimento do documento:</strong>
  <%= @ship.registration_due_date %>
</p>
  
<p>
  <strong>Cliente:</strong>
  <%= @ship.customer.name %>
</p>


<%= link_to 'Editar', edit_ship_path(@ship) %> |
<%= link_to 'Ir para a lista de embarcações', ships_path %>
<%= link_to 'Ir para a lista de clientes', customers_path %>